#!/usr/bin/env sh

# General settings
yabai -m config layout              stack
yabai -m config window_topmost      on
yabai -m config window_placement    second_child

# Appearance
yabai -m config window_shadow       off
yabai -m config window_border       off

# Spacing
yabai -m config top_padding         15
yabai -m config bottom_padding      15
yabai -m config left_padding        15
yabai -m config right_padding       15
yabai -m config window_gap          15

# Mouse support
yabai -m config mouse_modifier      fn
yabai -m config mouse_follows_focus on

# Applications
yabai -m rule --add app!="^(Google Chrome|iTerm2|Emacs|Microsoft Teams|IntelliJ IDEA |OBS)$" manage=off
